###
@token = {{login.response.body.accessToken}}

GET http://localhost:3000

### POST /
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "vertessymarton",
    "password": "123123213",
    "confirmPassword": "123123213"
}

###
# @name login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "vertessymarton",
    "password": "123123213"
}

###
# @name login
POST http://localhost:3000/auth/refresh

###
POST http://localhost:3000/auth/logout

###
POST http://localhost:3000/auth/logout/all

###
GET http://localhost:3000/todos?limit=15&listId=26&status=all
Authorization: Bearer {{token}}

###
GET http://localhost:3000/lists
Authorization: Bearer {{token}}

###
POST http://localhost:3000/todos
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "task": "masodik",
    "listId": 27
}

###
POST http://localhost:3000/lists
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "masodik"
}

###
PUT http://localhost:3000/lists/5
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "nigger"
}

###
PATCH  http://localhost:3000/todos/33
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "listId": "20"
}

###
PUT http://localhost:3000/todos/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "completed": true
}

###
DELETE http://localhost:3000/lists/5
Authorization: Bearer {{token}}

###
DELETE http://localhost:3000/todos/1
Authorization: Bearer {{token}}